spring.application.name=openink

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED}
spring.jpa.hibernate.ddl-auto=update
api.security.token.secret=${SECRET_TOKEN_API}
